modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="assorted_items"
version="1.0.0"
displayName="Assorted Ores"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Henry, MCreator"

[[dependencies.assorted_items]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




